### PR TITLE
Use sass for css 

### PR DESCRIPTION
**Pull request by kebbet**
I use sass command line tool to build css, but could be done automatically I guess? 

```sass/simple-smtp.scss assets/simple-smtp.css --style=compressed --watch  ```

### CODE REVIEW

**Comment by kebbet** [comment]
This is a follow up to #93

**Comment by soup-bowl** [comment]
I've branched in Jekyll lately so I'm now a lot more experienced with Sass, so I am more than happy for Sass to be used here and just makes the whole process a lot cleaner.

I'm currently snowed under, but when time permits I'll add it to the spin-up dev and build deployment CI/CDs.

**Comment by soup-bowl** [comment]
Needs one last re-sync to merge, as GitHub is not permitting me to do so. Not 100% sure why since the commits are ahead in the chain.

**Comment by kebbet** [comment]
Good morning @soup-bowl ! Conflicts sorted and tests fixed :)

**Comment by soup-bowl** [comment]
This has also been [added to the project wiki](https://github.com/soup-bowl/wp-simple-smtp/wiki/Development#styling-css-changes).

**Pull request merged**
