### PR TITLE
At a glance info

### PR DESCRIPTION
**Pull request by soup-bowl**
PR to roll in @kebbet's dashboard glance feature, showing a count of the emails currently found inside the log.

I had no doubts, but for completeness I've tested this on  singular and multisite instance, works fine in both use-cases.

### CODE REVIEW

**Comment by kebbet** [comment]
Main sass file could be updated to have a correct comment above the import of the glance file. But thats a really small minor thing :)

**Comment by kebbet** [comment]
And glance class could have correct @since tags when you settle on an new release version.

**Comment by soup-bowl** [comment]
> Main sass file could be updated to have a correct comment above the import of the glance file. But thats a really small minor thing :)

Added by my sleep-deprived commit mesage of "[aaaaaaaaaaaaaaaaa](https://github.com/soup-bowl/wp-simple-smtp/pull/103/commits/2fb75fcfe786f9f3a389aff05039e3df2d749a22)"

**Comment by soup-bowl** [comment]
> And glance class could have correct `@since` tags when you settle on an new release version.

I'll sort that out when I make the release branch :+1:

**Pull request merged**
