### PR TITLE
Add one.com to QuickConfig.

### PR DESCRIPTION
**Pull request by kebbet**
Title says it. One.com is quite commonly used in the scandinavian countries.

### CODE REVIEW

**Comment by soup-bowl** [comment]
Do you have a link to the SMTP configuration page on their documentation? I'm going to be adding (not sure if I've synced yet) a page for where to find the SMTP QC settings to make it easier to keep them up to date.

**Comment by kebbet** [comment]
Found this page, and of course are my PR incorrect. 

https://help.one.com/hc/en-us/articles/115005594305-Can-I-use-your-SMTP-server-to-send-emails-

**Comment by soup-bowl** [comment]
Much appreciated :)

**Comment by kebbet** [comment]
Strange thing though, with the options on the linked page enabled dispatch does not work. Only the ones I added in the PR seems to work. Maybe just close this PR.

**Pull request closed without merging**
